name: nmt-transformer-vs-rnn
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - pyyaml
      - pandas
      - matplotlib
      - huggingface_hub